[app-admin/collectd] Added oracle and checkconfig features to init script
(Portage version: 2.1.9.25/git/Linux i686, unsigned Manifest commit)

diff --git a/app-admin/collectd/files/collectd.initd b/app-admin/collectd/files/collectd.initd
--- a/app-admin/collectd/files/collectd.initd
+++ b/app-admin/collectd/files/collectd.initd
@@ -7,12 +7,42 @@
 : ${COLLECTD_CFGFILE:='/etc/collectd.conf'}
 : ${COLLECTD_NICELVL:='5'}
 
+opts="${opts} configtest"
 
 depend() {
 	use net
 }
 
+configtest() {
+	ebegin "Checking ${SVCNAME} configuration"
+	checkconfig
+	eend $?
+}
+
+checkconfig() {
+	if [[ $(sed '/^$\|^#/d' ${COLLECTD_CFGFILE} | grep -c 'LoadPlugin\w\+oracle') != 0 ]] ; then
+		if [[ -e /etc/env.d/50oracle-instantclient-basic ]] ; then
+			source /etc/env.d/50oracle-instantclient-basic
+		        export ORACLE_HOME
+		        export TNS_ADMIN
+		else
+			ewarn "Unable to set Oracle environment, Oracle plugin wont work"
+		fi
+	fi
+
+	/usr/sbin/collectd -t -C "${COLLECTD_CFGFILE}" 1>/dev/null 2>&1
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		eerror "${SVCNAME} has detected an error in your setup:"
+		/usr/sbin/collectd -t -C "${COLLECTD_CFGFILE}"
+	fi
+
+	return $ret
+}
+
 start() {
+	checkconfig || return 1
+
 	ebegin "Starting collectd"
 	start-stop-daemon --start \
 		--nicelevel "${COLLECTD_NICELVL}" --exec /usr/sbin/collectd -- \
